import { IconButton, Button as MUIButton, ToggleButtonGroup, } from "@mui/joy";
import { FieldLabel, registerOverlayPortal } from "@measured/puck";
import React, { useEffect, useRef } from 'react';
import type { Fields } from "@measured/puck";
import "@measured/puck/puck.css";
import { buttonResolvedFields } from "./fields";

const buttonDefaultProps = {
    action: 'REDIRECT',
    draggable: true,
    text: 'Click me',
    link: "https://afroallure.co/",
    fontSize: 1.1,
    fontWeight: 400,
    letterSpacing: 1.8,
    lineHeight: 1.5,
    color: '#000000',
    style: [],
    fontFamily: 'Inter',
    align: 'start',
    gapX: 0,
    variant: 'solid',
    gapY: 0,
    padding: 2,
    borderRadiusExpanded: 'false',
    borderRadiusTopLeft: 0,
    borderRadiusTopRight: 0,
    borderRadiusBottomLeft: 0,
    borderRadiusBottomRight: 0,
    paddingExpanded: "true",
    marginExpanded: "false",
    marginBottom: 0,
    marginLeft: 0,
    marginRight: 0,
    marginTop: 0,
    margin: 0,
    paddingBottom: 1,
    paddingLeft: 2,
    paddingRight: 2,
    paddingTop: 1,
    backgroundColor: '#d2d2d2',
    borderColor: '#000000',
    borderRadius: 8,
    borderWidth: 1,
    borderBottom: 0,
    borderExpanded: 'false',
    borderLeft: 0,
    borderRight: 0,
    borderTop: 0,
    numOfCols: 3,
    numOfRows: 3,
    borderType: 'solid',
    positionType: 'relative',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    responsive: true,
    flexDirection: 'flex-row',
    mainAxisLayout: 'start',
    altAxisLayout: 'start',
}


export const ButtonComponent: any = {
    resolveFields: buttonResolvedFields,
    defaultProps: buttonDefaultProps,
    render: ({ text, link, action, padding, margin, backgroundColor, flexDirection, mainAxisLayout, altAxisLayout, paddingTop, paddingBottom, paddingExpanded, paddingLeft, paddingRight, positionType, top, bottom, left, right, borderColor, borderRadius, borderType, borderWidth, gapX, gapY, numOfCols, numOfRows, marginExpanded, marginTop, marginBottom, marginLeft, marginRight, borderExpanded, borderBottom, borderLeft, borderRight, borderTop, borderRadiusExpanded, borderRadiusBottomLeft, borderRadiusBottomRight, borderRadiusTopLeft, borderRadiusTopRight, fontSize, fontWeight, fontFamily, color, letterSpacing, lineHeight, style, id, align }: any) => {
        const ref = useRef<any>(null);
        useEffect(() => registerOverlayPortal(ref.current), [ref.current]);
        return <MUIButton href={link} target="_blank" ref={ref} rel="noopener noreferrer" sx={{
            padding: `${padding}rem`,
            paddingTop: paddingExpanded === 'true' ? `${paddingTop}rem` : `${padding}rem`,
            paddingBottom: paddingExpanded === 'true' ? `${paddingBottom}rem` : `${padding}rem`,
            paddingRight: paddingExpanded === 'true' ? `${paddingRight}rem` : `${padding}rem`,
            paddingLeft: paddingExpanded === 'true' ? `${paddingLeft}rem` : `${padding}rem`,
            margin: `${margin}rem`,
            marginTop: marginExpanded === 'true' ? `${marginTop}rem` : `${margin}rem`,
            marginBottom: marginExpanded === 'true' ? `${marginBottom}rem` : `${margin}rem`,
            marginRight: marginExpanded === 'true' ? `${marginRight}rem` : `${margin}rem`,
            marginLeft: marginExpanded === 'true' ? `${marginLeft}rem` : `${margin}rem`,
            backgroundColor,
            position: positionType,
            top,
            bottom,
            left,
            right,
            justifyContent: mainAxisLayout,
            alignItems: altAxisLayout,
            borderRadius,
            borderTopLeftRadius: borderRadiusExpanded === 'true' ? borderRadiusTopLeft : borderRadius,
            borderTopRightRadius: borderRadiusExpanded === 'true' ? borderRadiusTopRight : borderRadius,
            borderBottomLeftRadius: borderRadiusExpanded === 'true' ? borderRadiusBottomLeft : borderRadius,
            borderBottomRightRadius: borderRadiusExpanded === 'true' ? borderRadiusBottomRight : borderRadius,
            borderStyle: borderType,
            borderColor,
            borderWidth,
            borderTop: borderExpanded === 'true' ? `${borderTop}` : `${borderWidth}`,
            borderBottom: borderExpanded === 'true' ? `${borderBottom}` : `${borderWidth}`,
            borderRight: borderExpanded === 'true' ? `${borderRight}` : `${borderWidth}`,
            borderLeft: borderExpanded === 'true' ? `${borderLeft}` : `${borderWidth}`,
            columnGap: gapX,
            rowGap: gapY,
            display: flexDirection === 'grid' ? 'grid' : 'flex',
            gridTemplateColumns: `repeat(${numOfCols}, minmax(0, 1fr))`,
            gridTemplateRows: `repeat(${numOfRows}, minmax(0, 1fr))`,
            textWrap: 'wrap',
            fontSize: `${fontSize}rem`,
            fontFamily,
            fontWeight: style?.includes('bold') ? 'bold' : fontWeight,
            color,
            letterSpacing,
            lineHeight,
            textAlign: align,
            textDecoration: style?.includes('underline') ? 'underline' : "none",
            fontStyle: style?.includes('italic') ? 'italic' : 'normal'
        }} className={`apply-font-${id.split('-')[1]} max-w-max`}>
            {text}
        </MUIButton>
    }
}
