import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserWrapper } from "@utils/context/UserContext";
import { NextUIProvider } from "@nextui-org/react";
import '@fontsource/inter';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Afro Allure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserWrapper>
          <NextUIProvider>
            {children}
          </NextUIProvider>
        </UserWrapper>
      </body>
    </html>

  );
}
