import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { UserWrapper } from "@utils/context/UserContext";
import { NextUIProvider } from "@nextui-org/react";
import '@fontsource/inter';
import Script from 'next/script'


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Afro Allure",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const GA_ID = process.env.NEXT_PUBLIC_GA_MEASUREMENT_ID

  return (
    <html lang="en">
      <head>
        {GA_ID && (
          <>
            {/* Load the GA script */}
            <Script
              src={`https://www.googletagmanager.com/gtag/js?id=${GA_ID}`}
              strategy="afterInteractive"
            />
            {/* Initialize GA */}
            <Script id="gtag-init" strategy="afterInteractive">
              {`
                window.dataLayer = window.dataLayer || [];
                function gtag(){dataLayer.push(arguments);}
                gtag('js', new Date());
                gtag('config', '${GA_ID}', { page_path: window.location.pathname });
              `}
            </Script>
          </>
        )}
      </head>
      <body className={inter.className}>
        <UserWrapper>
          <NextUIProvider>
            {children}
          </NextUIProvider>
        </UserWrapper>
      </body>
    </html>

  );
}
