export const galleryDefaultProps = [
    {
        type: 'Image',
        props: {
            url: 'https://jappbqntqogmnoluifzx.supabase.co/storage/v1/object/public/editor-media-pool/placeholder_photo.jpg',
            width: 100,
            borderColor: '#000000',
            borderRadius: 8,
            borderWidth: 1,
            borderType: 'solid',
            positionType: 'relative',
            left: 0,
            right: 0,
            top: 0,
            bottom: 0,
            borderRadiusTopLeft: 0,
            borderRadiusTopRight: 0,
            borderRadiusBottomLeft: 0,
            borderRadiusBottomRight: 0,
            borderBottom: 0,
            borderExpanded: 'false',
            borderLeft: 0,
            borderRadiusExpanded: 'false',
            borderRight: 0,
            borderTop: 0,
        }
    },
    {
        type: 'Image',
        props: {
            url: 'https://jappbqntqogmnoluifzx.supabase.co/storage/v1/object/public/editor-media-pool/placeholder_photo.jpg',
            width: 100,
            borderColor: '#000000',
            borderRadius: 8,
            borderWidth: 1,
            borderType: 'solid',
            positionType: 'relative',
            left: 0,
            right: 0,
            top: 0,
            bottom: 0,
            borderRadiusTopLeft: 0,
            borderRadiusTopRight: 0,
            borderRadiusBottomLeft: 0,
            borderRadiusBottomRight: 0,
            borderBottom: 0,
            borderExpanded: 'false',
            borderLeft: 0,
            borderRadiusExpanded: 'false',
            borderRight: 0,
            borderTop: 0,
        }
    },
    {
        type: 'Image',
        props: {
            url: 'https://jappbqntqogmnoluifzx.supabase.co/storage/v1/object/public/editor-media-pool/placeholder_photo.jpg',
            width: 100,
            borderColor: '#000000',
            borderRadius: 8,
            borderWidth: 1,
            borderType: 'solid',
            positionType: 'relative',
            left: 0,
            right: 0,
            top: 0,
            bottom: 0,
            borderRadiusTopLeft: 0,
            borderRadiusTopRight: 0,
            borderRadiusBottomLeft: 0,
            borderRadiusBottomRight: 0,
            borderBottom: 0,
            borderExpanded: 'false',
            borderLeft: 0,
            borderRadiusExpanded: 'false',
            borderRight: 0,
            borderTop: 0,
        }
    },
    {
        type: 'Image',
        props: {
            url: 'https://jappbqntqogmnoluifzx.supabase.co/storage/v1/object/public/editor-media-pool/placeholder_photo.jpg',
            width: 100,
            borderColor: '#000000',
            borderRadius: 8,
            borderWidth: 1,
            borderType: 'solid',
            positionType: 'relative',
            left: 0,
            right: 0,
            top: 0,
            bottom: 0,
            borderRadiusTopLeft: 0,
            borderRadiusTopRight: 0,
            borderRadiusBottomLeft: 0,
            borderRadiusBottomRight: 0,
            borderBottom: 0,
            borderExpanded: 'false',
            borderLeft: 0,
            borderRadiusExpanded: 'false',
            borderRight: 0,
            borderTop: 0,
        }
    },
    {
        type: 'Image',
        props: {
            url: 'https://jappbqntqogmnoluifzx.supabase.co/storage/v1/object/public/editor-media-pool/placeholder_photo.jpg',
            width: 100,
            borderColor: '#000000',
            borderRadius: 8,
            borderWidth: 1,
            borderType: 'solid',
            positionType: 'relative',
            left: 0,
            right: 0,
            top: 0,
            bottom: 0,
            borderRadiusTopLeft: 0,
            borderRadiusTopRight: 0,
            borderRadiusBottomLeft: 0,
            borderRadiusBottomRight: 0,
            borderBottom: 0,
            borderExpanded: 'false',
            borderLeft: 0,
            borderRadiusExpanded: 'false',
            borderRight: 0,
            borderTop: 0,
        }
    },
    {
        type: 'Image',
        props: {
            url: 'https://jappbqntqogmnoluifzx.supabase.co/storage/v1/object/public/editor-media-pool/placeholder_photo.jpg',
            width: 100,
            borderColor: '#000000',
            borderRadius: 8,
            borderWidth: 1,
            borderType: 'solid',
            positionType: 'relative',
            left: 0,
            right: 0,
            top: 0,
            bottom: 0,
            borderRadiusTopLeft: 0,
            borderRadiusTopRight: 0,
            borderRadiusBottomLeft: 0,
            borderRadiusBottomRight: 0,
            borderBottom: 0,
            borderExpanded: 'false',
            borderLeft: 0,
            borderRadiusExpanded: 'false',
            borderRight: 0,
            borderTop: 0,
        }
    },
]
